export const RECORDS_PER_PAGE = 12;
export const MAX_DISPLAY_PAGE = 2;
export const MAX_ALLOWED_ATTR_VALUE = 50;
export const MAX_PROD_IMAGE_UPLOAD = 10;
export const MAX_IMAGE_SIZE = 3 * 1024 * 1024; // 3MB
export const MAX_PRODUCT_PRICE = 1000000000;
export const MAX_PRODUCT_STOCK = 400000;
export const NUM_DAYS_PRODUCT_NEW = 30; // Number of days to consider a product as new
export const MAX_BANNER_IMAGE_UPLOAD = 10;
